### ISSUE TITLE
panic when testing

### ISSUE THREAD

**Issue by chaos369** [anacrolix/confluence#26]
It's panic after these steps. But can't be reproduced because of the data cached, maybe.

1 http://192.168.3.6:9982/info?ih=08ada5a7a6183aae1e09d831df6748d566095a10

2 http://192.168.3.6:9982/data?magnet=magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&path=Sintel.mp4

3 http://192.168.3.6:9982/fileState?ih=08ada5a7a6183aae1e09d831df6748d566095a10&path=Sintel.mp4
```
root@ubuntu:/usr/local/go/bin# ./confluence -addr=:9982
2021/01/11 01:06:30 main.go:64: open packed-blocklist: no such file or directory
2021/01/11 01:06:30 main.go:204: serving http at [::]:9982
2021-01-11T01:06:36+0000 NONE  client.go:368: dht server on [::]:50007 completed bootstrap (dht.TraversalStats{NumAddrsTried:9, NumResponses:0})
2021/01/11 01:06:54 server.go:3061: http: panic serving 192.168.3.26:53029: runtime error: invalid memory address or nil pointer dereference
goroutine 560 [running]:
net/http.(*conn).serve.func1(0xc0000b9ae0)
	/usr/local/go/src/net/http/server.go:1772 +0x139
panic(0xd3da20, 0x1556630)
	/usr/local/go/src/runtime/panic.go:973 +0x3e3
github.com/anacrolix/torrent/metainfo.(*MetaInfo).UpvertedAnnounceList(0x0, 0xc000779f20, 0x30, 0x31d8091eae3a18a6)
	/root/workspace/pkg/mod/github.com/anacrolix/torrent@v1.17.2-0.20201013023405-07bc79dbdc03/metainfo/metainfo.go:83 +0x26
main.mainErr.func4(0xc00030d400, 0x0)
	/root/workspace/pkg/mod/github.com/anacrolix/confluence@v1.6.1/main.go:215 +0xa1
github.com/anacrolix/confluence/confluence.(*Handler).withTorrentContext.func1(0xf7f500, 0xc000390380, 0xc0002b0200)
	/root/workspace/pkg/mod/github.com/anacrolix/confluence@v1.6.1/confluence/middlewares.go:78 +0x32f
net/http.HandlerFunc.ServeHTTP(0xc000260b20, 0xf7f500, 0xc000390380, 0xc0002b0200)
	/usr/local/go/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00020e658, 0xf7f500, 0xc000390380, 0xc0002b0200)
	/usr/local/go/src/net/http/server.go:2387 +0x1a5
github.com/anacrolix/confluence/confluence.(*Handler).ServeHTTP(0xc00020e630, 0xf7f500, 0xc000390380, 0xc0002b0200)
	/root/workspace/pkg/mod/github.com/anacrolix/confluence@v1.6.1/confluence/handler.go:28 +0x5d
net/http.serverHandler.ServeHTTP(0xc000390000, 0xf7f500, 0xc000390380, 0xc0002b0200)
	/usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc0000b9ae0, 0xf820c0, 0xc000098580)
	/usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x35c
^@^@
```

**Comment by anacrolix** [comment]
This was fixed in d12e7797718d3092f853e58c7e94e29b8e7dce9c. I've pushed v1.7.0 to include this. Thanks!
